apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.3
        ports:
        - containerPort: 80     
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"


        volumeMounts:
        - mountPath: "usr/share/nginx/html/data"
          name: test-pv-storage
        - name: defaultconf
          mountPath: "/etc/nginx/conf.d"
          readOnly: true
      volumes:
      - name: defaultconf
        configMap:
          name: text-file
      - name: test-pv-storage
        persistentVolumeClaim:
          claimName: test-pv-claim




---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: text-file
data:
  default.conf: |
    server {
    listen       80;
    server_name  localhost;


    location / {
        root   /usr/share/nginx/html/data;
        index  data.txt index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
    }